### ISSUE TITLE
Create a github account

### ISSUE THREAD

**Issue by remyabel** [remyabel/ENC3246-iFixit#1]
Reply here. We'll use this as a practice issue so everyone can get their feet wet.

**Comment by remyabel** [comment]
Added Kris (@KDLGates) as a contributor.

**Comment by KDLGates** [comment]
Still waiting on GitHub support for tracking all my personal issues.

**Comment by remyabel** [comment]
Added Jason (@jebber)

**Comment by remyabel** [comment]
Added Victor (@victorchang1993)
