### ISSUE TITLE
Proposal

### ISSUE THREAD

**Issue by remyabel** [remyabel/ENC3246-iFixit#12]
http://edu.ifixit.com/standard-project-proposal/

Sample proposal: https://static1.squarespace.com/static/557b6db2e4b0ff7f4a623e48/t/58adcd4dbe6594924e39e675/1487785293417/EDU+Example+Proposal.pdf

- What device will you be working on?
- How much repair information is already on the internet about your device? 
- What are your proposed page titles?
- What specific topics will you address on your troubleshooting page?
- What specific guides will you write for your device?
- Which camera will you be using?

**Comment by KDLGates** [comment]
Updated issues for #16
