### ISSUE TITLE
[#12] Header

### ISSUE THREAD

**Issue by remyabel** [remyabel/ENC3246-iFixit#13]
This is a sub-issue of #12.

Device:
Team tag:
Camera:
Group email addresses:

The full name of the device must either be gleaned from the device's iFixit sticker or the manufacturer's web page. For the camera, mention the mega-pixels.

- [x] Device's full name
- [x] Camera

**Comment by victorchang1993** [comment]
tnguyen16@mail.usf.edu
kdlgates@kdlgates.com
jberroth@mail.usf.edu
victorchang@mail.usf.edu
