### ISSUE TITLE
[#12] Specific troubleshooting topics

### ISSUE THREAD

**Issue by remyabel** [remyabel/ENC3246-iFixit#16]
This is a sub-issue of #12.

- [x] Unreliable or Unresponsive Motion Detection
- [x] Connectivity Troubleshooting and Wi-Fi Outages / Automatic Switching
- [x] Updating the Canary Firmware and App Software
- [x] Unresponsiveness in Setup Mode and Pairing Bluetooth (Original Canary)
- [x] Reducing / Silencing / Customizing Security Alert Notifications

**Comment by KDLGates** [comment]
The intent here is that I'll use the Canary Community support board as a base for troubleshooting topics, try to cross-reference it a little bit, and try to come up with the top issues that I think real users are searching for. Will post the results over the weekend.

**Comment by remyabel** [comment]
The [Milestone 1](http://edu.ifixit.com/milestone-1-research/) page has some good tips. Right now I'm going to collate some Q&A sites here:

**Q&A**

http://www.bestbuy.com/site/questions/canary-indoor-wi-fi-high-definition-all-in-one-home-security-system-black/9967102

https://www.amazon.com/Canary-All-One-Security-Device/dp/B00NW31YSE - Customer question & answers

**Reviews**

https://www.amazon.com/Canary-All-One-Security-Device/product-reviews/B00NW31YSE/ref=cm_cr_arp_d_viewopt_sr?ie=UTF8&reviewerType=avp_only_reviews&pageNumber=1&filterByStar=critical - Negative reviews that might contain problems we can research

http://www.securitycamerareviews.net/tag/can100usbk/ - A negative review that contains lots of problems with the device

**Comment by KDLGates** [comment]
Added topics.

**Comment by remyabel** [comment]
Kris, thanks for the update. Remember it should be "[#16] Add troubleshooting topics" and it'll appear automatically here. I'll fix it after Victor gets his info in.

**Comment by remyabel** [comment]
Kris, I meant the commit message itself. i.e, Update proposal -> [#16] Add troubleshooting topics. It has to be done manually from the command line which is why I sent that e-mail.

**Comment by KDLGates** [comment]
Gotcha. I wasn't aware GitHub would pick up a commit description with an arrow to the issue it's addressing, that's pretty neat.

**Comment by remyabel** [comment]
I'm re-opening the issue because most of them seem to be for the Flex (not the CAN100USBK). Example: http://community.canary.is/search?q=battery

Ideally the issues should be stuff like (audio is distorted) and not help desk support (restart/reinstall app, etc.)

**Comment by KDLGates** [comment]
Good catch on the Flex battery. Switched it out with the best replacement issue I could find on short notice (folks bothered by excessive motion alerts).

I agree that issues should ideally be related to the replacement guides, but I think it's a challenge that we wouldn't actually be able to test any fixes. At least with common troubleshooting issues we can post reliable steps.

**Comment by remyabel** [comment]
Still, the troubleshooting topics need to be phrased as user-observed symptoms not support questions. i.e, instead of "Connectivity troubleshooting and wifi outages" it should be "Weak or lost wireless connections". This [article from the Canary FAQ](https://help.canary.is/hc/en-us/articles/204772717-Why-can-t-Canary-hear-my-device-) is actually pretty similar to how an iFixit article would be structured.

I think we can keep the wi-fi one. Firmware needs to be a solution rather than a topic: for example, "device is running slow" so "update firmware". Unresponsiveness can be kept if the answers don't amount to "restart the app" and reducing security notifications is a configuration issue, unless the underlying cause is a problem with the device itself. We still got 3 days to work on this (including Tuesday) so I'm going to keep this open still.
