### ISSUE TITLE
[Team Charter #3] Unacceptable work

### ISSUE THREAD

**Issue by remyabel** [remyabel/ENC3246-iFixit#8]
This is a sub-issue of #3.

- [x] Unacceptable Work

**Comment by KDLGates** [comment]
I am tempted to check the "Unacceptable Work" box purely as an example of unacceptable work.

**Comment by KDLGates** [comment]
Drafted the Unacceptable Work section of the charter and checkmarked the Unacceptable Work.

If this work counts as unacceptable, then this is an open and shut case of irony.

**Comment by remyabel** [comment]
Looks good. Only complaint is the comma usage but we can revise that later when we all have coffee in our systems.
